CREATE TABLE consumos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    pago_id BIGINT,
    cantidad INTEGER NOT NULL,
    precio_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    estado_pago VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_consumos_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id),
    CONSTRAINT fk_consumos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_consumos_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
    CONSTRAINT fk_consumos_pago FOREIGN KEY (pago_id) REFERENCES pagos(id)
);

CREATE INDEX idx_consumos_reserva ON consumos(reserva_id);
CREATE INDEX idx_consumos_pago ON consumos(pago_id);
