CREATE TABLE torneos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    formato VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    max_parejas INTEGER NOT NULL,
    precio_inscripcion DECIMAL(10,2) NOT NULL,
    descripcion VARCHAR(500),
    estado VARCHAR(50) NOT NULL DEFAULT 'INSCRIPCION_ABIERTA',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_torneos_estado ON torneos(estado);
CREATE INDEX idx_torneos_categoria ON torneos(categoria);
