CREATE TABLE inscripciones_torneo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id BIGINT NOT NULL,
    jugador1_id BIGINT NOT NULL,
    jugador2_id BIGINT NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'CONFIRMADA',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_inscripciones_torneo FOREIGN KEY (torneo_id) REFERENCES torneos(id),
    CONSTRAINT fk_inscripciones_jugador1 FOREIGN KEY (jugador1_id) REFERENCES usuarios(id),
    CONSTRAINT fk_inscripciones_jugador2 FOREIGN KEY (jugador2_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_inscripciones_torneo ON inscripciones_torneo(torneo_id);
