CREATE TABLE partidos_torneo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id BIGINT NOT NULL,
    ronda VARCHAR(100) NOT NULL,
    numero_ronda INTEGER NOT NULL,
    inscripcion1_id BIGINT NOT NULL,
    inscripcion2_id BIGINT,
    fecha_hora TIMESTAMP,
    sets_pareja1 INTEGER,
    sets_pareja2 INTEGER,
    ganador_inscripcion_id BIGINT,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_partidos_torneo FOREIGN KEY (torneo_id) REFERENCES torneos(id),
    CONSTRAINT fk_partidos_inscripcion1 FOREIGN KEY (inscripcion1_id) REFERENCES inscripciones_torneo(id),
    CONSTRAINT fk_partidos_inscripcion2 FOREIGN KEY (inscripcion2_id) REFERENCES inscripciones_torneo(id),
    CONSTRAINT fk_partidos_ganador FOREIGN KEY (ganador_inscripcion_id) REFERENCES inscripciones_torneo(id)
);

CREATE INDEX idx_partidos_torneo ON partidos_torneo(torneo_id);
CREATE INDEX idx_partidos_numero_ronda ON partidos_torneo(numero_ronda);
