CREATE TABLE ranking_jugadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jugador_id BIGINT NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    puntos INTEGER NOT NULL DEFAULT 0,
    partidos_jugados INTEGER NOT NULL DEFAULT 0,
    partidos_ganados INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_ranking_jugador FOREIGN KEY (jugador_id) REFERENCES usuarios(id),
    CONSTRAINT uk_ranking_jugador_categoria UNIQUE (jugador_id, categoria)
);

CREATE INDEX idx_ranking_categoria ON ranking_jugadores(categoria);
