CREATE TABLE solicitudes_partido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creador_id BIGINT NOT NULL,
    tipo_solicitud VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    cantidad_jugadores_faltantes INTEGER NOT NULL,
    fecha_hora_propuesta TIMESTAMP NOT NULL,
    cancha_id BIGINT,
    descripcion VARCHAR(500),
    estado VARCHAR(50) NOT NULL DEFAULT 'ABIERTA',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_solicitudes_creador FOREIGN KEY (creador_id) REFERENCES usuarios(id),
    CONSTRAINT fk_solicitudes_cancha FOREIGN KEY (cancha_id) REFERENCES canchas(id)
);

CREATE INDEX idx_solicitudes_categoria ON solicitudes_partido(categoria);
CREATE INDEX idx_solicitudes_estado ON solicitudes_partido(estado);
