CREATE TABLE postulaciones_solicitud (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id BIGINT NOT NULL,
    jugador_id BIGINT NOT NULL,
    mensaje VARCHAR(300),
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_postulaciones_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitudes_partido(id),
    CONSTRAINT fk_postulaciones_jugador FOREIGN KEY (jugador_id) REFERENCES usuarios(id),
    CONSTRAINT uk_postulacion_solicitud_jugador UNIQUE (solicitud_id, jugador_id)
);

CREATE INDEX idx_postulaciones_solicitud ON postulaciones_solicitud(solicitud_id);
