CREATE TABLE canchas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    tipo_suelo VARCHAR(50) NOT NULL,
    techada BOOLEAN NOT NULL,
    tiene_luz BOOLEAN NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_canchas_nombre ON canchas(nombre);
CREATE INDEX idx_canchas_activa ON canchas(activa);
