CREATE TABLE franjas_horarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id BIGINT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    duracion_min INTEGER NOT NULL,
    precio_base DECIMAL(10,2) NOT NULL,
    precio_nocturno DECIMAL(10,2) NOT NULL,
    dias_aplicables VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_franjas_cancha FOREIGN KEY (cancha_id) REFERENCES canchas(id)
);

CREATE INDEX idx_franjas_cancha ON franjas_horarias(cancha_id);
