CREATE TABLE bloqueos_canchas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancha_id BIGINT NOT NULL,
    fecha_desde DATE NOT NULL,
    fecha_hasta DATE NOT NULL,
    hora_desde TIME NOT NULL,
    hora_hasta TIME NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bloqueos_cancha FOREIGN KEY (cancha_id) REFERENCES canchas(id)
);

CREATE INDEX idx_bloqueos_cancha ON bloqueos_canchas(cancha_id);
