CREATE TABLE reservas (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          usuario_id BIGINT NOT NULL,
                          cancha_id BIGINT NOT NULL,
                          franja_id BIGINT NOT NULL,
                          fecha DATE NOT NULL,
                          hora_inicio TIME NOT NULL,
                          hora_fin TIME NOT NULL,
                          precio_total DECIMAL(10,2) NOT NULL,
                          estado_reserva VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE_PAGO',
                          origen VARCHAR(50) NOT NULL,
                          motivo_cancelacion VARCHAR(255),
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP,
                          CONSTRAINT fk_reservas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
                          CONSTRAINT fk_reservas_cancha FOREIGN KEY (cancha_id) REFERENCES canchas(id),
                          CONSTRAINT fk_reservas_franja FOREIGN KEY (franja_id) REFERENCES franjas_horarias(id)
);

CREATE INDEX idx_reservas_usuario ON reservas(usuario_id);
CREATE INDEX idx_reservas_cancha ON reservas(cancha_id);
CREATE INDEX idx_reservas_fecha ON reservas(fecha);
CREATE INDEX idx_reservas_estado ON reservas(estado_reserva);

-- COMENTADO TEMPORALMENTE PARA COMPATIBILIDAD CON H2
-- Se descomentará en la Fase 6 cuando migremos definitivamente a PostgreSQL físico.
-- CREATE UNIQUE INDEX idx_reservas_unicas_confirmadas
-- ON reservas (cancha_id, fecha, hora_inicio)
-- WHERE estado_reserva IN ('CONFIRMADA', 'COMPLETADA');