CREATE TABLE bonos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    horas_totales INTEGER NOT NULL,
    horas_usadas INTEGER NOT NULL DEFAULT 0,
    precio_pagado DECIMAL(10,2) NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bonos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE INDEX idx_bonos_usuario ON bonos(usuario_id);
CREATE INDEX idx_bonos_estado ON bonos(estado);
