CREATE TABLE uso_bono (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bono_id BIGINT NOT NULL,
    reserva_id BIGINT NOT NULL,
    horas_descontadas INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_uso_bono_bono FOREIGN KEY (bono_id) REFERENCES bonos(id),
    CONSTRAINT fk_uso_bono_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id)
);

CREATE INDEX idx_uso_bono_bono ON uso_bono(bono_id);
CREATE INDEX idx_uso_bono_reserva ON uso_bono(reserva_id);
