spring:
  application:
    name: padelapp-backend
  profiles:
    active: dev # Perfil por defecto en desarrollo local
  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

jwt:
  secret: ${JWT_SECRET:9a7261b4a6824147bc961726a45b8109d949b29c92cf8cfb183bfcaef296fa22}
  expiration: ${JWT_EXPIRATION:86400000}
